## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 400bit
        url: jdbc:postgresql://localhost/postgres
        platform: postgres
        initialization-mode: always
        continue-on-error: true
  jpa:
    show-sql: false
#    generate-ddl: false
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  #      dialect: org.hibernate.dialect.MySQL5Dialect
  #  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: localhost
#    port: 6379
#  freemarker:
#      cache: false



jwtSecret: me.zhulin
jwtExpiration: 86400
queries:
  users-query: select email, password, active from users where email=?
  roles-query: select email, role from users where email=?


